### ISSUE TITLE
WordPress Slide

### ISSUE THREAD

**Issue by josephbona** [jlengstorf/hyper-optimized-workflow-slides#1]
Very helpful slideshow. Do you have the info on using this workflow with 'Regular WordPress Sites'? Looks like you just demo'd it in your presentation when you got to that slide so I was wondering if you had it documented anywhere?

Thanks!

**Comment by jlengstorf** [comment]
Holy shit, dude. I'm so sorry I never got back to you on this. I just now saw this issue for the first time. 😞 

I assume it's probably too little too late here, but [this WordPress site](https://github.com/jlengstorf/thenategreenexperience.com/tree/master/site/web/app/themes/nge2016) is using a Gulp setup that, while it's evolved a little from what this presentation covers, will handle all the JavaScript and CSS bundling/linting/minification for a theme, as well as image compression and some other cleanup.

Let me know if you have other questions. I'll be paying attention now, I swear. 😄

**Comment by josephbona** [comment]
No worries! Thanks for the response..I ended up making my own file structure and set up but I'll checkout the repo and see how you're doing things.

Thanks again
